dist: xenial
language: python
cache: pip
before_install:
  - pip install -U tox

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8


script: tox
